# PBS configuration
queue: normal
project: e14
walltime: 5:00:00
jobname: minimal_01deg_jra55_ryf
ncpus: 2064

shortpath: /short/x77

# Model configuration
name: common
model: access-om2
input: /short/public/access-om2/input_08022019/common_01deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /short/public/access-om2/bin/yatm_b77aecd2.exe
      input: /short/public/access-om2/input_08022019/yatm_01deg
      ncpus: 1

    - name: ocean
      model: mom
      exe: /short/public/access-om2/bin/fms_ACCESS-OM_2a69f46f_libaccessom2_b77aecd2.x
      input:
          - /short/public/access-om2/input_08022019/minimal_mom_01deg
          - /short/public/access-om2/input_08022019/mom_01deg
      ncpus: 1717

    - name: ice
      model: cice5
      exe: /short/public/access-om2/bin/cice_auscom_3600x2700_722p_47650cc7_libaccessom2_b77aecd2.exe
      input:
          - /short/public/access-om2/input_08022019/cice_01deg
      ncpus: 335

# Collation
collate: true
collate_walltime: 10:00:00
collate_mem: 128GB
collate_ncpus: 4
collate_queue: expressbw
collate_flags: -n4 -z -m -r

mpirun: --mca orte_base_help_aggregate 0

# Misc
runlog: False
stacksize: unlimited
qsub_flags: -lother=hyperthread -W umask=027
mpi:
    module: openmpi/1.10.2
