# PBS configuration
queue: normalbw
project: x77
walltime: 1:00:00
jobname: minimal_01deg_jra55_ryf
ncpus: 2156
mem: 9850Gb
shortpath: /short/x77

# Model configuration
name: common
model: access-om2
input: /short/public/access-om2/input_38570c62/common_01deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /short/public/access-om2/bin/yatm_e8ad3723.exe
      input: /short/public/access-om2/input_38570c62/yatm_01deg
      ncpus: 1

    - name: ocean
      model: mom
      exe: /short/public/access-om2/bin/fms_ACCESS-OM_afe80bfd.x
      input:
          - /short/public/access-om2/input_38570c62/minimal_mom_01deg
          - /short/public/access-om2/input_38570c62/mom_01deg
      ncpus: 1717

    - name: ice
      model: cice5
      exe: cice_auscom_3600x2700_400p.exe
      input: /short/public/access-om2/input_38570c62/cice_01deg
      ncpus: 432

# Collation
collate: true
collate_walltime: 10:00:00
collate_mem: 128GB
collate_ncpus: 4
collate_queue: expressbw
collate_flags: -n4 -z -m -r

mpirun: --mca orte_base_help_aggregate 0

# Misc
runlog: False
stacksize: unlimited
qsub_flags: -lother=hyperthread -W umask=027
mpi:
    module: openmpi/1.10.2
