# PBS configuration
queue: normal
# project: v45
walltime: 5:00:00
jobname: minimal_01deg_jra55_ryf
ncpus: 2064
# shortpath: /short/v45

# Model configuration
name: common
model: access-om2
input: /short/public/access-om2/input_rc/common_01deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /short/public/access-om2/bin/yatm_b77aecd2.exe
      input: /short/public/access-om2/input_rc/yatm_01deg
      ncpus: 1

    - name: ocean
      model: mom
      exe: /short/public/access-om2/bin/fms_ACCESS-OM_2a69f46f_libaccessom2_b77aecd2.x
      input:
          - /short/public/access-om2/input_rc/minimal_mom_01deg
          - /short/public/access-om2/input_rc/mom_01deg
      ncpus: 1717

    - name: ice
      model: cice5
      exe: /short/public/access-om2/bin/cice_auscom_3600x2700_722p_47650cc7_libaccessom2_b77aecd2.exe
      input: /short/public/access-om2/input_rc/cice_01deg
      ncpus: 335

# Collation
collate:
  walltime: 10:00:00
  mem: 128GB
  ncpus: 4
  queue: expressbw
  restart: True
  exe: /short/public/access-om2/bin/mppnccombine

# Misc
runlog: True
stacksize: unlimited
restart_freq: 1  # use tidy_restarts.py instead
mpirun: --mca orte_base_help_aggregate 0
qsub_flags: -W umask=027
mpi:
    module: openmpi/1.10.2
platform:
    nodesize: 16
    nodemem: 64

# DANGER! Do not uncomment this without checking the script is synching to the correct location!
# postscript: sync_to_gdata.sh
